### ISSUE TITLE
15 Buckets get destroyed when one is filled

### ISSUE THREAD

**Issue by Staegrin** [VincentHuto/Lava-Mo-Tron#1]
So versions: hutoslib-5.2.3
                  lavamotron-3.2.0
                  minecraft 1.20.1
                  Neoforge 47.1.76
Description:
15 buckets get destroyed and replaced with one bucket of lava

How to reproduce:
1) Use a hopper to insert buckets into the lavamotron 16 buckets can be inserted this way. Unlike when manually you can only insert 1 bucket.
![2023-11-12_18 25 26](https://github.com/VincentHuto/Lava-Mo-Tron/assets/8494635/80f7b521-dd59-406e-bbe7-df79e1cefce6)
![2023-11-12_18 27 32](https://github.com/VincentHuto/Lava-Mo-Tron/assets/8494635/5fdcc2dc-5a4e-463f-8544-f0f54b0acd9b)

2) Produce some lava
64 buckets get turned into 4 buckets of lava
 
![2023-11-12_18 25 29](https://github.com/VincentHuto/Lava-Mo-Tron/assets/8494635/7b1e0435-f1f8-4ae6-97e4-5b32c9a7a4de)

How to solve:
Prevent hoppers from inserting more than 1 bucket or make the created lava bucket appear in the slot where thermal shards are created.

**Comment by VincentHuto** [comment]
Oh good call, I had not done to much automation testing since I had redone the GUI, Ill take a look, I also fixed the other bug already so that will be put out with this one

**Comment by Staegrin** [comment]
Thanks. Keep up the good work.

**Comment by VincentHuto** [comment]
@Staegrin  Fixed with https://legacy.curseforge.com/minecraft/mc-mods/lava-mo-tron/files/4862561 release :)

**Comment by Staegrin** [comment]
Minor issue caused by the fix. If there is only one bucket in the bottom right slot. The filled bucket will not go to the output slot. 
![2023-11-12_20 43 37](https://github.com/VincentHuto/Lava-Mo-Tron/assets/8494635/bd433684-52f9-4eae-a647-5b7cf4223a11)
It can still be extracted on the right side when this happens, but that would also mean you would need to extract at the bottom and the right side at the same time to extract all lava buckets.

**Comment by VincentHuto** [comment]
Alright, Ill take another look in a bit, thanks for finding these

**Comment by VincentHuto** [comment]
@Staegrin Version 3.2.2 is under review by curse now, should be public within the housr

**Comment by Staegrin** [comment]
Works great
