### ISSUE TITLE
Lava-Mo-Tron can not be collected/mined

### ISSUE THREAD

**Issue by Staegrin** [VincentHuto/Lava-Mo-Tron#2]
So versions: hutoslib-5.2.3
lavamotron-3.2.0
minecraft 1.20.1
Neoforge 47.1.76
Description:
When breaking a Lava-Mo-Tron, even with a netherite pickaxe with silk touch the block is destroyed. So once placed the block can not be removed and placed elsewhere.

How to reproduce:
1) Place a Lava-Mo-Tron
2) Mine the Lava-Mo-Tron with a pickaxe 
3) Block is destroyed and doesn't drop the item form

How to solve:
Add a loot table to the breaking of the block

**Comment by VincentHuto** [comment]
Ah the loot table must have gotten deleted by accident, ill make a quick fix now

**Comment by Staegrin** [comment]
Now dropping when mined. Keep up the good work.
